import { describe, expect, expectTypeOf, it } from "vitest";
import {
  GroupHistoryTree,
  groupWithdrawnNotificationsByCommit,
  type AuditContextOptions,
  type AuditSink,
  type AppliedNotificationsIngestResult,
  type ConvergenceScheduler,
  type EdgeSnapshot,
  type HistoryEdge,
  type HistoryNode,
  type RetainedHistoryStore,
  type StateInvalidatedIngestResult,
  type StateNotification,
  type TimerHandle,
} from "../index.js";
import * as exports from "../index.js";

type RootSignatureTypes =
  | StateNotification
  | AppliedNotificationsIngestResult
  | StateInvalidatedIngestResult
  | AuditContextOptions
  | AuditSink
  | ConvergenceScheduler
  | EdgeSnapshot
  | HistoryEdge
  | HistoryNode
  | RetainedHistoryStore
  | TimerHandle;

describe("exports", () => {
  it("should name every root public-signature symbol from the root", () => {
    expectTypeOf<RootSignatureTypes>().not.toBeNever();
    expectTypeOf(GroupHistoryTree).toBeConstructibleWith();
    expectTypeOf(groupWithdrawnNotificationsByCommit).toBeFunction();
  });

  it("should export the expected members", () => {
    expect(Object.keys(exports).sort()).toMatchInlineSnapshot(`
      [
        "ACCOUNT_IDENTITY_PROOF_EVENT_KIND",
        "ACCOUNT_IDENTITY_PROOF_EXTENSION_TYPE",
        "ADDRESSABLE_KEY_PACKAGE_KIND",
        "AGENT_TEXT_STREAM_QUIC_COMPONENT",
        "AGENT_TEXT_STREAM_QUIC_COMPONENT_ID",
        "AGENT_TEXT_STREAM_QUIC_FANOUT_EXTENSION_TYPE",
        "AGENT_TEXT_STREAM_QUIC_RECEIVE_EXTENSION_TYPE",
        "AGENT_TEXT_STREAM_QUIC_ROLE_EXTENSION_TYPES",
        "AGENT_TEXT_STREAM_QUIC_SEND_EXTENSION_TYPE",
        "AGENT_TEXT_STREAM_ROLE_FANOUT",
        "AGENT_TEXT_STREAM_ROLE_RECEIVE",
        "AGENT_TEXT_STREAM_ROLE_SEND",
        "APP_COMPONENTS_COMPONENT_ID",
        "BLOSSOM_LOCATOR_KIND",
        "BLOSSOM_LOCATOR_KIND_V1",
        "BinaryDecodeError",
        "BinaryReader",
        "BinaryWriter",
        "BoundedIdCache",
        "DEFAULT_CONVERGENCE_POLICY",
        "DEFAULT_GROUP_COMPONENT_IDS",
        "ENCRYPTED_MEDIA_FORMAT_V1",
        "ENCRYPTED_MEDIA_VERSION",
        "GIFT_WRAP_KIND",
        "GROUP_ADMIN_POLICY_COMPONENT",
        "GROUP_ADMIN_POLICY_COMPONENT_ID",
        "GROUP_AVATAR_URL_COMPONENT",
        "GROUP_AVATAR_URL_COMPONENT_ID",
        "GROUP_BLOSSOM_IMAGE_COMPONENT",
        "GROUP_BLOSSOM_IMAGE_COMPONENT_ID",
        "GROUP_DESCRIPTION_MAX_BYTES",
        "GROUP_ENCRYPTED_MEDIA_COMPONENT",
        "GROUP_ENCRYPTED_MEDIA_COMPONENT_ID",
        "GROUP_EVENT_KIND",
        "GROUP_LIFECYCLE_COMPONENT",
        "GROUP_LIFECYCLE_COMPONENT_ID",
        "GROUP_MESSAGE_RETENTION_COMPONENT",
        "GROUP_MESSAGE_RETENTION_COMPONENT_ID",
        "GROUP_NAME_MAX_BYTES",
        "GROUP_PROFILE_COMPONENT",
        "GROUP_PROFILE_COMPONENT_ID",
        "GroupHistoryTree",
        "GroupMediaService",
        "GroupMediaStore",
        "GroupRumorHistory",
        "GroupRuntime",
        "GroupSession",
        "GroupTerminalError",
        "GroupsManager",
        "INBOX_RELAY_LIST_KIND",
        "INBOX_RELAY_TAG",
        "InviteManager",
        "KEY_PACKAGE_APP_COMPONENTS_TAG",
        "KEY_PACKAGE_CIPHER_SUITE_TAG",
        "KEY_PACKAGE_CLIENT_TAG",
        "KEY_PACKAGE_EXTENSIONS_TAG",
        "KEY_PACKAGE_MLS_VERSION_TAG",
        "KEY_PACKAGE_PROPOSALS_TAG",
        "KEY_PACKAGE_RELAYS_TAG",
        "KeyPackageManager",
        "KeyPackageNotFoundError",
        "KeyPackagePublisher",
        "KeyPackageRotatePreconditionError",
        "KeyPackageStore",
        "LAST_RESORT_EXTENSION_TYPE",
        "MAX_VARINT",
        "MarmotClient",
        "MarmotGroup",
        "MarmotGroupEngine",
        "MissingRelayError",
        "MissingSlotIdentifierError",
        "NIP65_RELAY_LIST_KIND",
        "NIP65_RELAY_TAG",
        "NOSTR_GROUP_ID_TAG",
        "NOSTR_ROUTING_COMPONENT",
        "NOSTR_ROUTING_COMPONENT_ID",
        "NoGroupRelaysError",
        "NoMarmotGroupDataError",
        "NostrWelcomeDelivery",
        "Proposals",
        "SAFE_AAD_COMPONENT_ID",
        "SUPPORTED_APP_COMPONENT_IDS",
        "SUPPORTED_LOCATOR_KINDS",
        "WELCOME_EVENT_KIND",
        "accountIdentityProofEventId",
        "accountIdentityProofEventJson",
        "accountIdentityProofSignatureFromSignedEvent",
        "accountIdentityProofSigningDigest",
        "adminPolicyEntry",
        "agentTextStreamEntry",
        "appComponentsEntry",
        "buildAccountIdentityProofEvent",
        "buildAccountIdentityProofExtension",
        "buildAppDataDictionary",
        "buildFallbackFetchUrls",
        "buildForkTreeView",
        "calculateKeyPackageRef",
        "canTransitionLifecycle",
        "canonicalizeMimeType",
        "classifyDisbandCommit",
        "classifyLateCommit",
        "collectAppDataUpdateOps",
        "commitDigest",
        "compareBranchScores",
        "compareCommitOrderingKeys",
        "componentEntry",
        "convergenceOutcomeToCategory",
        "createAdminCommitPolicyCallback",
        "createApplicationMessageIntent",
        "createChatRumor",
        "createCredential",
        "createDefaultKeyPackageLifetime",
        "createDeleteKeyPackageEvent",
        "createEncryptedGroupEventContent",
        "createGiftWrap",
        "createGroup",
        "createGroupEvent",
        "createInboxRelayListEvent",
        "createInviteIntent",
        "createKeyPackageEvent",
        "createNip65RelayListEvent",
        "createSimpleGroup",
        "createThreeMonthLifetime",
        "createWelcomeRumor",
        "decideCommitAuthorization",
        "decodeAccountIdentityProof",
        "decodeAdminPolicyV1",
        "decodeAgentTextStreamQuicPolicyV1",
        "decodeComponentsList",
        "decodeContent",
        "decodeEncryptedMediaPolicyV1",
        "decodeGroupAvatarUrlV1",
        "decodeGroupLifecycleV1",
        "decodeGroupProfileV1",
        "decodeMessageRetentionV1",
        "decodeNostrRoutingV1",
        "decodeUtf8",
        "decodeVarint",
        "decryptGroupMessage",
        "decryptGroupMessageEvent",
        "decryptGroupMessages",
        "decryptMediaFile",
        "decryptMediaFileWithKeys",
        "defaultCapabilities",
        "defaultMarmotClientConfig",
        "deferredReasons",
        "deriveMediaEncryptionKey",
        "deserializeApplicationData",
        "deserializeApplicationRumor",
        "deserializeClientState",
        "detectEncoding",
        "disposition",
        "encodeAccountIdentityProof",
        "encodeAdminPolicyV1",
        "encodeAgentTextStreamQuicPolicyV1",
        "encodeComponentsList",
        "encodeContent",
        "encodeEncryptedMediaPolicyV1",
        "encodeGroupAvatarUrlV1",
        "encodeGroupLifecycleV1",
        "encodeGroupProfileV1",
        "encodeMediaImetaTag",
        "encodeMessageRetentionV1",
        "encodeNostrRoutingV1",
        "encodeUtf8",
        "encodeVarint",
        "encryptMediaFile",
        "encryptedMediaBlossomDefault",
        "encryptedMediaEntry",
        "ensureLastResortExtension",
        "ensureMarmotCapabilities",
        "evaluateKeyPackageForGroup",
        "extendedExtensionTypes",
        "formatMlsTimestamp",
        "generateKeyPackage",
        "getAdminPolicy",
        "getAgentTextStreamPolicy",
        "getAppComponents",
        "getComponentData",
        "getCredentialLeafNodeIndexes",
        "getCredentialPubkey",
        "getEncodingTag",
        "getEncryptedMediaPolicy",
        "getEpoch",
        "getGroupAvatarUrl",
        "getGroupIdHex",
        "getGroupLifecycle",
        "getGroupMemberPubkeys",
        "getGroupMembers",
        "getGroupProfile",
        "getInboxRelays",
        "getKeyPackage",
        "getKeyPackageCipherSuiteId",
        "getKeyPackageClient",
        "getKeyPackageExtensions",
        "getKeyPackageIdentifier",
        "getKeyPackageLifetime",
        "getKeyPackageMLSVersion",
        "getKeyPackageNostrPubkey",
        "getKeyPackageReference",
        "getKeyPackageRelays",
        "getMarmotGroupInfo",
        "getMarmotGroupView",
        "getMediaAttachments",
        "getMemberCount",
        "getMessageRetention",
        "getNip65Relays",
        "getNostrGroupIdHex",
        "getNostrRouting",
        "getPubkeyLeafNodeIndexes",
        "getPubkeyLeafNodes",
        "getTagValue",
        "getWelcome",
        "getWelcomeGroupRelays",
        "getWelcomeKeyPackageEventId",
        "getWelcomeKeyPackageRefs",
        "groupAvatarUrlEntry",
        "groupLifecycleEntry",
        "groupLifecycleStates",
        "groupProfileEntry",
        "groupProtocolLifecycleValues",
        "groupWithdrawnNotificationsByCommit",
        "hasAck",
        "ingestResultDisposition",
        "inputCategories",
        "isAppPayloadExpired",
        "isApplicationMessage",
        "isBranchEligible",
        "isCommitMessage",
        "isHexKey",
        "isLastResortExtension",
        "isLifetimeCurrentWithGrace",
        "isLifetimeValid",
        "isLifetimeWithinCap",
        "isProposalMessage",
        "isSameCredential",
        "isValidAccountIdentity",
        "isValidInboxRelayListEvent",
        "isValidNip65RelayListEvent",
        "isValidRelayUrl",
        "isWitnessEligible",
        "keyPackageDefaultExtensions",
        "makeAccountIdentityProofExtension",
        "makeAppComponentsExtension",
        "makeLeafAppComponentsExtension",
        "marmotRequiredCapabilitiesExtension",
        "mayApplyRetainedInbound",
        "mayPrepareLocalCommit",
        "mayRunForkDetection",
        "messageRetentionEntry",
        "mlsSignatureScheme",
        "normalizeConvergencePolicy",
        "normalizeRelayUrl",
        "nostrRoutingEntry",
        "nostrTransportBinding",
        "parseMediaImetaTag",
        "prunableRetainedEpochs",
        "readWelcomeGroupInfo",
        "readWelcomeMarmotGroupView",
        "replaceExtension",
        "requiredRetainedEpochs",
        "resolveMediaFetchUrls",
        "scoreBranch",
        "selectCanonicalBranch",
        "selectFairQueuedStateIntent",
        "selectFetchableLocators",
        "serializeApplicationRumor",
        "serializeClientState",
        "signAccountIdentityProof",
        "sortGroupCommits",
        "transitionLifecycle",
        "unixNow",
        "validateAdminLeafCoupling",
        "validateAppComponentIntegrity",
        "validateCommitLegality",
        "validateConvergencePolicy",
        "varintSize",
        "verifyAllLeafAccountIdentityProofs",
        "verifyApplicationRumorAuthorship",
        "verifyLeafAccountIdentityProof",
      ]
    `);
  });
});
